web:
  build: .
  command: develop
  volumes:
    - .:/sustainable_cities
  ports:
    - '3000:3000'
  links:
    - postgres
  env_file: dev.env

postgres:
  image: postgres
  container_name: postgres_sustainable_cities

redis:
  image: redis
  container_name: redis_sustainable_cities
