version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    environment:
      PORT: 3000
      RAILS_ENV: staging
      RACK_ENV: staging
    ports:
      - "3003:3000"
    container_name: sc_api_legacy
    volumes:
      - "./public/system:/usr/src/app/public/system"
      - "./public/uploads:/usr/src/app/public/uploads"
      - "./log:/usr/src/app/log"
