version: '2'
services:
  app:
    build: .
    command: bundle exec puma -C config/puma.rb
    env_file: .env
    environment:
      PORT: 3000
      RAILS_ENV: production
      RACK_ENV: production
    ports:
      - "3002:3000"
    container_name: sc_api
    volumes:
      - "./public/system:/usr/src/app/public/system"
      - "./public/uploads:/usr/src/app/public/uploads"
      - "./log:/usr/src/app/log"
